import type { EditorMeta } from "@/editors/types";

export const meta: EditorMeta = {
	id: "plate",
	name: "Plate",
	tagline:
		"Slate-based plugin framework (MIT) with a shadcn-style copy-in UI registry — the biggest free feature set of the four.",
	homepage: "https://platejs.org",
	packages: [
		"platejs",
		"@platejs/basic-nodes",
		"@platejs/basic-styles",
		"@platejs/callout",
		"@platejs/caption",
		"@platejs/code-block",
		"@platejs/code-drawing",
		"@platejs/combobox",
		"@platejs/comment",
		"@platejs/date",
		"@platejs/dnd",
		"@platejs/docx",
		"@platejs/emoji",
		"@platejs/excalidraw",
		"@platejs/floating",
		"@platejs/footnote",
		"@platejs/indent",
		"@platejs/juice",
		"@platejs/layout",
		"@platejs/link",
		"@platejs/list",
		"@platejs/markdown",
		"@platejs/math",
		"@platejs/media",
		"@platejs/mention",
		"@platejs/resizable",
		"@platejs/selection",
		"@platejs/slash-command",
		"@platejs/suggestion",
		"@platejs/table",
		"@platejs/toc",
		"@platejs/toggle",
		"@excalidraw/excalidraw",
		"@ariakit/react",
		"react-dnd",
		"react-dnd-html5-backend",
		"remark-gfm",
		"remark-math",
		"remark-emoji",
		"@emoji-mart/data",
		"lowlight",
		"katex",
		"html2canvas-pro",
		"pdf-lib",
		"use-file-picker",
		"react-day-picker",
		"radix-ui",
	],
	uiApproach:
		"Official Plate UI registry (`shadcn add @plate/plate-ui` + ~35 kits) vendored into src/editors/plate/{ui,components,hooks,lib} and composed into our own EditorKit without AIKit/CopilotKit. We edited the vendored files: AI buttons/menus removed, uploadthing replaced by base64 data URLs, mention combobox fed from USERS, a Template group (Variable/Mention) + Image/Divider added to the slash menu, mention/variable nodes emit the shared data attributes. The {{variable}} chip, its `{{` picker and the markdown rules are our own plugin.",
	features: {
		marks: {
			status: "kit",
			note: "Bold/italic/underline/strike/code/highlight/kbd/sub/sup + font colour, background, size via the registry toolbars.",
		},
		headings: { status: "kit" },
		lists: {
			status: "kit",
			note: "Plate lists are indent-based paragraphs (`listStyleType` + `indent`), not nested ul/li nodes.",
		},
		"task-list": { status: "kit" },
		link: {
			status: "kit",
			note: "Floating link toolbar, ⌘K, autolink on paste.",
		},
		blockquote: { status: "kit" },
		"code-block": {
			status: "kit",
			note: "lowlight syntax highlighting with language picker.",
		},
		table: {
			status: "kit",
			note: "Cell selection, merge, column resize, row/column menus.",
		},
		image: {
			status: "custom",
			note: "Registry media kit (resize, caption, preview); its uploadthing hook was replaced with fileToDataUrl — >1 MB shows a toast and removes the placeholder.",
		},
		"undo-redo": { status: "builtin" },
		"slash-menu": { status: "kit" },
		"drag-handle": {
			status: "kit",
			note: "@platejs/dnd + react-dnd; also drops into columns and drops files.",
		},
		"floating-toolbar": { status: "kit" },
		"fixed-toolbar": { status: "kit" },
		"markdown-shortcuts": {
			status: "kit",
			note: "Autoformat kit: #, -, 1., [], >, ```, ---, **bold**, `code`, smart quotes, arrows.",
		},
		mention: {
			status: "kit",
			note: "Registry mention combobox fed from USERS; markdown rule replaced so labels keep `[@Label](mention:id)` exactly.",
		},
		variable: {
			status: "custom",
			note: "Our inline-void plugin (createSlatePlugin + toPlatePlugin), `{{` trigger via an insertText override, picker built on the registry InlineCombobox, slash item, static node, remark plugin + MdRules.",
		},
		"markdown-import": {
			status: "builtin",
			note: "@platejs/markdown (remark + MDX). `{{x}}` on its own line becomes an MDX flow expression → its own paragraph.",
		},
		"markdown-export": {
			status: "partial",
			note: "Idempotent round-trip on the sample, but toggle, code drawing and excalidraw blocks (and indentation of plain paragraphs) are silently dropped; Plate-only blocks export as MDX tags (<callout>, <column_group>, <toc />, <date />).",
		},
		"html-export": {
			status: "builtin",
			note: "serializeHtml from platejs/static with the static kit (async, renders React to a string).",
		},
		"static-render": {
			status: "builtin",
			note: "<PlateStatic> (EditorStatic) with the base kit — no editor instance or DOM selection.",
		},
		ssr: {
			status: "partial",
			note: 'Route module imports only meta + React.lazy chunks; the editor is client-only. Vite 8\'s SSR dep optimizer still crawls the lazy chunk, so @platejs/docx-io (htmlparser2@3 `require("../")`) crashed the dev server and had to be removed.',
		},
		"thai-ime": {
			status: "partial",
			note: "manual check — Playwright keyboard.type of Thai works, but that is not a real IME composition.",
		},
	},
	showcase: [
		"Block selection: click beside blocks or drag a selection rectangle, then right-click for the block context menu (delete, duplicate, turn into, indent, align).",
		"Comments and suggestions (local only): select text → comment or switch the mode menu to Suggesting to track insertions/deletions with accept/reject.",
		"Columns, toggles, callouts and an auto-updating table of contents (“Insert showcase blocks” below adds them).",
		"Math (KaTeX block + inline), dates with a calendar picker, footnotes, emoji picker (:), font colour/background/size, line height, alignment.",
		"Excalidraw whiteboard and code drawings (Mermaid / PlantUML / Graphviz) as blocks via the slash menu.",
		"Import HTML/Markdown files and export HTML / PDF / PNG / Markdown from the toolbar; Word/Google Docs paste cleanup via @platejs/docx + juice (wired, not tested here).",
	],
	findings: [
		"The registry is a lot of code: ~190 vendored files; `editor-kit` pulls AI (@platejs/ai), Copilot and uploadthing by default — we deleted ai-node/ai-toolbar-button, edited 7 files to drop AIChatPlugin, and rewrote use-upload-file. @platejs/ai, uploadthing, @uploadthing/react (and zod) are no longer imported.",
		'@platejs/docx-io (Word import/export) depends on html-to-vdom → htmlparser2@3, whose `require("../")` the Vite 8 / rolldown dep optimizer cannot resolve; the SSR optimizer hits it even behind React.lazy and kills the dev server. We removed Word import/export (paste from Word via @platejs/docx still works).',
		"Markdown is good but not lossless for Plate-only blocks: toggle, code_drawing and excalidraw have no MdRules and are dropped with a console.warn('Unreachable code'); combobox input/placeholder nodes too, so we strip them before serializing.",
		"MDX is on by default in the markdown kit, so `{{name}}` parses as an mdxTextExpression (handled in our remark plugin) and a `{{x}}` line directly under a paragraph line becomes a separate paragraph; soft line breaks export as hard breaks (`\\`). After one export the markdown is stable (round-trip lossless).",
		"Plate's built-in mention markdown uses the link text as the label including the `@`, and remarkMention also turns any bare `@word` into a mention — replaced with our own remark plugin + rules.",
		"Registry static list component adds margin-left for DOCX on top of the indent plugin margin, so static ordered lists were double-indented; fixed in the vendored file. The registry code-drawing base kit also used the interactive component.",
		"Empty table cells export as a zero-width space (U+200B); tables export with `| - |` delimiter rows (we disabled pipe alignment).",
		"Bundle (vite build): the lazy plate-editor chunk is 1.93 MB minified / 568 KB gzip + 157 KB CSS on the client, before the separately lazy-loaded excalidraw/mermaid chunks; the SSR/worker build also bundles it (4.3 MB) even though it never renders on the server.",
		"serializeHtml is async and renders the whole static tree through React; we run it on a 120 ms debounce on a separate headless editor. The HTML carries all Tailwind classes and data-slate-* attributes (~40 KB for the sample).",
		"Vitest: @platejs/math imports katex.min.css from its dist, which Node cannot load when vitest externalizes the package — our unit test mocks @platejs/math.",
		"Types: one registry TS error out of the box (date-node `initialFocus` → `autoFocus` for react-day-picker 10); otherwise strict TS 6 + React 19 clean.",
	],
};
