/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlocknoteRouteImport } from './routes/blocknote'
import { Route as LexicalRouteImport } from './routes/lexical'
import { Route as PlateRouteImport } from './routes/plate'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as TiptapRouteImport } from './routes/tiptap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocknoteRoute = BlocknoteRouteImport.update({
  id: '/blocknote',
  path: '/blocknote',
  getParentRoute: () => rootRouteImport,
} as any)
const LexicalRoute = LexicalRouteImport.update({
  id: '/lexical',
  path: '/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateRoute = PlateRouteImport.update({
  id: '/plate',
  path: '/plate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TiptapRoute = TiptapRouteImport.update({
  id: '/tiptap',
  path: '/tiptap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocknote': typeof BlocknoteRoute
  '/lexical': typeof LexicalRoute
  '/plate': typeof PlateRoute
  '/research': typeof ResearchRoute
  '/tiptap': typeof TiptapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocknote': typeof BlocknoteRoute
  '/lexical': typeof LexicalRoute
  '/plate': typeof PlateRoute
  '/research': typeof ResearchRoute
  '/tiptap': typeof TiptapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocknote': typeof BlocknoteRoute
  '/lexical': typeof LexicalRoute
  '/plate': typeof PlateRoute
  '/research': typeof ResearchRoute
  '/tiptap': typeof TiptapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/blocknote' | '/lexical' | '/plate' | '/research' | '/tiptap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blocknote' | '/lexical' | '/plate' | '/research' | '/tiptap'
  id:
    | '__root__'
    | '/'
    | '/blocknote'
    | '/lexical'
    | '/plate'
    | '/research'
    | '/tiptap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocknoteRoute: typeof BlocknoteRoute
  LexicalRoute: typeof LexicalRoute
  PlateRoute: typeof PlateRoute
  ResearchRoute: typeof ResearchRoute
  TiptapRoute: typeof TiptapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocknote': {
      id: '/blocknote'
      path: '/blocknote'
      fullPath: '/blocknote'
      preLoaderRoute: typeof BlocknoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexical': {
      id: '/lexical'
      path: '/lexical'
      fullPath: '/lexical'
      preLoaderRoute: typeof LexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plate': {
      id: '/plate'
      path: '/plate'
      fullPath: '/plate'
      preLoaderRoute: typeof PlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiptap': {
      id: '/tiptap'
      path: '/tiptap'
      fullPath: '/tiptap'
      preLoaderRoute: typeof TiptapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocknoteRoute: BlocknoteRoute,
  LexicalRoute: LexicalRoute,
  PlateRoute: PlateRoute,
  ResearchRoute: ResearchRoute,
  TiptapRoute: TiptapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
