import type { EditorId } from "@/editors/types";

/**
 * Client JS each editor route loads on top of the app shell (route chunks + every dependency,
 * including ones another editor also uses), gzip. Generated by `pnpm bundle-sizes`; do not edit by hand.
 */
export const BUNDLE_SIZES: Partial<
	Record<EditorId, { rawKb: number; gzipKb: number }>
> = {
	plate: {
		rawKb: 4426,
		gzipKb: 1336,
	},
	blocknote: {
		rawKb: 2659,
		gzipKb: 754,
	},
	lexical: {
		rawKb: 2526,
		gzipKb: 709,
	},
	tiptap: {
		rawKb: 2024,
		gzipKb: 539,
	},
};
