import type { EditorId } from "@/editors/types";

/**
 * Client JS each editor route loads on top of the app shell (route chunks + every dependency,
 * including ones another editor also uses), gzip. Generated by `pnpm bundle-sizes`; do not edit by hand.
 */
export const BUNDLE_SIZES: Partial<
	Record<EditorId, { rawKb: number; gzipKb: number }>
> = {
	plate: {
		rawKb: 4299,
		gzipKb: 1294,
	},
	blocknote: {
		rawKb: 1109,
		gzipKb: 339,
	},
	lexical: {
		rawKb: 2048,
		gzipKb: 553,
	},
	tiptap: {
		rawKb: 1790,
		gzipKb: 467,
	},
};
