import type { EditorId } from "@/editors/types";

/**
 * Client JS unique to each editor route (route chunks + dependencies not shared with the app shell
 * or another editor route), gzip. Generated by `pnpm bundle-sizes`; do not edit by hand.
 */
export const BUNDLE_SIZES: Partial<
	Record<EditorId, { rawKb: number; gzipKb: number }>
> = {
	plate: {
		rawKb: 1,
		gzipKb: 1,
	},
	blocknote: {
		rawKb: 1,
		gzipKb: 1,
	},
	lexical: {
		rawKb: 1,
		gzipKb: 1,
	},
	tiptap: {
		rawKb: 1,
		gzipKb: 1,
	},
};
